import type { LucideIcon } from 'lucide-react'
import {
  AppWindowMac,
  ShoppingCart,
  Building2,
  Palette,
  Code2,
  Smartphone,
  LayoutDashboard,
  Zap,
  Search,
  BarChart3,
  PenTool,
  LineChart,
  Gauge,
  CreditCard,
  Package,
  Truck,
  Shield,
  Rocket,
  FileText,
  Lightbulb,
  Leaf,
  Target,
  Bolt,
  Brain,
  ClipboardList,
  Wand2,
  Layers,
  Sparkles,
  Heart,
  Users,
  Eye,
  MessageCircle,
  CheckCircle2,
  ArrowRight,
  Star,
} from 'lucide-react'

// CMS stores icon names; this map resolves them to Lucide components.
export const iconMap: Record<string, LucideIcon> = {
  layout: AppWindowMac,
  'shopping-cart': ShoppingCart,
  palette: Palette,
  'building2': Building2,
  code: Code2,
  smartphone: Smartphone,
  dashboard: LayoutDashboard,
  zap: Zap,
  search: Search,
  'bar-chart': BarChart3,
  'pen-tool': PenTool,
  'line-chart': LineChart,
  gauge: Gauge,
  'credit-card': CreditCard,
  package: Package,
  truck: Truck,
  shield: Shield,
  rocket: Rocket,
  'file-text': FileText,
  lightbulb: Lightbulb,
  leaf: Leaf,
  target: Target,
  bolt: Bolt,
  brain: Brain,
  'clipboard-list': ClipboardList,
  wand: Wand2,
  layers: Layers,
  sparkles: Sparkles,
  heart: Heart,
  users: Users,
  eye: Eye,
  message: MessageCircle,
  'check-circle': CheckCircle2,
  'arrow-right': ArrowRight,
  star: Star,
  check: CheckCircle2,
}

export function resolveIcon(name?: string | null, fallback: LucideIcon = Sparkles): LucideIcon {
  return (name ? iconMap[name] : undefined) ?? fallback
}
