/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: d6ecb3c90444b0ec1f36f979c6ad24fb)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	R2: R2Bucket;
	D1: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	CLOUDFLARE_DEPLOY: "true";
	ENVIRONMENT: "staging" | "production";
	PAYLOAD_PUBLIC_SERVER_URL?: "https://cms-captiveau-staging.mulaiplus.workers.dev";
	NEXTJS_ENV: string;
	WORKER_SELF_REFERENCE: Fetcher /* cms-captiveau-staging */ | Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface StagingEnv {
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		R2: R2Bucket;
		D1: D1Database;
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		CLOUDFLARE_DEPLOY: "true";
		ENVIRONMENT: "staging";
		PAYLOAD_PUBLIC_SERVER_URL: "https://cms-captiveau-staging.mulaiplus.workers.dev";
		NEXTJS_ENV: string;
		WORKER_SELF_REFERENCE: Fetcher /* cms-captiveau-staging */;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_DEPLOY" | "ENVIRONMENT" | "PAYLOAD_PUBLIC_SERVER_URL" | "NEXTJS_ENV">> {}
}
