/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 49cb02c83698d68031f52b65d516abee)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	R2: R2Bucket;
	D1: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	NEXTJS_ENV: string;
	WORKER_SELF_REFERENCE: Fetcher /* cms-captiveau */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV">> {}
}
