allowBuilds:
  esbuild: false
  sharp: true
  workerd: true
onlyBuiltDependencies: '["esbuild","sharp","workerd"]'
patchedDependencies:
  '@payloadcms/drizzle': patches/@payloadcms__drizzle.patch
  '@payloadcms/next': patches/@payloadcms__next.patch